### ISSUE TITLE
Compatibility with Mendix Modeler 7.6

### ISSUE THREAD

**Issue by Mocke44** [mendix/FileDocumentViewer#11]
Hi,

I recently converted one of our apps to run on Mx 7.6.
After the conversion the testers logged a bug on the documents. It seems in Mx 7.6 when displaying the document in a form that an error occurs, because the document does not display and the document title displays [Object] [object] instead of the actual title. 
Also after this happens the document seems to get corrupted as downloading the document causes a Null Pointer error in the console and nothing happens in the browser.

After removing the Widget from the form, the error no longer occurs, i have ability to download the pdf, and also sending the document as an attachment on an Email.

Any help would be greatly appreciated :)

Kind regards,

Ryan Mocke.

**Comment by mkumpf** [comment]
Ryan,
This error is due to a deprecated function call in the javascript for the widget.  I encountered the same error.  I have submitted a pull request to update this function call as needed for MX 7.6.  

In the meantime, I've made a version of the widget.  You can download it here:  http://www.filehosting.org/file/details/693888/FileDocumentViewer.mpk  

Let me know if you have any questions.
Mike

**Comment by Mocke44** [comment]
Thanks Mike, 

I am downloading your updated version now, will let you know if it works :)

**Comment by JelteMX** [comment]
@mkumpf Can you show me the pull request?

**Comment by Mocke44** [comment]
Hey Mike,

Tested and working in IE, Firefox, Chrome and Microsoft EDGE.
Thanks for your help in this issue!

**Comment by JelteMX** [comment]
Keeping this open until I know what the fix is.

**Comment by JelteMX** [comment]
Fixed in [2.2.5](https://github.com/mendix/FileDocumentViewer/releases/tag/v2.2.5)

**Comment by mkumpf** [comment]
Jelte,
Did you find the Pull Request?  If not, let me know and I will resend it.
Mike

**Comment by mkumpf** [comment]
Oops, sorry about that - I made the pull request into my branch of this repository.

**Comment by JelteMX** [comment]
Ah, thanks. I checked it. You did: `mx.session.sessionData.csrftoken`, I used `mx.session.getConfig("csrftoken")`, which is the same thing essentially. Thanks anyway, it is fixed in the new version :-)
