### ISSUE TITLE
DocumentViewer not working when page has a URL defined

### ISSUE THREAD

**Issue by bartrikers** [mendix/FileDocumentViewer#13]
Hi,

The documentviewer isn't working when there is a url configured for the page.
For example, we have a page with the url /processstep/{Id}

The documentviewer then looks for the file
http://localhost:8080/p/processstep/file?target=window&guid=32932572275148853&csrfToken=834b7080-c3d6-4459-b74d-7de6dc142a2a&time=1510237475446

instead of

http://localhost:8080/file?target=window&guid=32932572275148953&csrfToken=b079b3ba-42a4-4ad9-8056-aeae17c52b70&time=1510237611044

**Comment by JelteMX** [comment]
I reproduced the issue, will see how I can fix it.

**Comment by JelteMX** [comment]
Fixed in [v2.2.7](https://github.com/mendix/FileDocumentViewer/releases/tag/v2.2.7), also in the AppStore

**Comment by bartrikers** [comment]
Great! Thanks for the (extremely) quick fix!

Bart Rikers
bart.rikers@bizzomate.com<mailto:bart.rikers@bizzomate.com>
+31 (0)6 33 82 74 36

[http://bizzomate.com/signature/twitter.png]<https://twitter.com/bizzomate>     [http://bizzomate.com/signature/linkedin.png] <https://www.linkedin.com/in/bartrikers>      [http://bizzomate.com/signature/skype_fb.png] <sip:bart.rikers@bizzomate.com>    [sign_web] <http://www.bizzomate.com/>

Van: Jelte Lagendijk [mailto:notifications@github.com]
Verzonden: donderdag 9 november 2017 16:14
Aan: mendix/FileDocumentViewer <FileDocumentViewer@noreply.github.com>
CC: Bart Rikers <bart.rikers@bizzomate.com>; Author <author@noreply.github.com>
Onderwerp: Re: [mendix/FileDocumentViewer] DocumentViewer not working when page has a URL defined (#13)


Fixed in v2.2.7<https://github.com/mendix/FileDocumentViewer/releases/tag/v2.2.7>, also in the AppStore
